openapi: 3.0.3
info:
  version: 0.6.1
  contact: {}
  title: Vic.Api
  description: |
    Vic.Api allows you to connect an *ERP* to the Vic.ai product suite.

servers:
- url: 'https://api.us.dev.vic.ai/v1'
  description: 'development server, US'
- url: 'https://api.no.dev.vic.ai/v1'
  description: 'development server, NO'
- url: 'https://api.us.stage.vic.ai/v1'
  description: 'staging server, US'
- url: 'https://api.no.stage.vic.ai/v1'
  description: 'staging server, NO'
- url: 'https://api.us.vic.ai/v1'
  description: 'production server, US'
- url: 'https://api.no.vic.ai/v1'
  description: 'production server, NO'

tags:
- name: purchase orders
- name: subscriptions

paths:
  /purchase_orders:
    post:
      description: Use this request to create a purchase order
      summary: Create a purchase order
      operationId: createPurchaseOrder
      tags:
        - purchase orders
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreatePurchaseOrder"
      responses:
        '200':
          description: Purchase order created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PurchaseOrder'
        default:
          $ref: "#/components/responses/ErrorResponse"
  /purchase_orders/{id}:
    get:
      description: Use this request to get data for a single purchase order
      summary: Get a purchase order
      operationId: getPurchaseOrder
      tags:
        - purchase orders
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
        - name: use_system
          in: query
          schema:
            $ref: "#/components/schemas/SystemType"
      responses:
        '200':
          description: Purchase order retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PurchaseOrder'
        default:
          $ref: "#/components/responses/ErrorResponse"
  /subscriptions:
    get:
      operationId: list_subscriptions
      description: List all subscriptions.
      tags:
      - subscriptions
      responses:
        "200":
          description: List all of the subscriptions
          content:
            application/json:
              schema:
                required:
                - data
                properties:
                  data:
                    type: array
                    items:
                      $ref: "#/components/schemas/Subscription"
        default:
          $ref: "#/components/responses/ErrorResponse"
    post:
      operationId: create_subscription
      description: Create a subscription.
      tags:
      - subscriptions
      requestBody:
        $ref: "#/components/requestBodies/CreateSubscription"
      responses:
        "201":
          description: Subscription was created successfully.
          content:
            application/json:
              schema:
                required:
                - data
                properties:
                  data:
                    $ref: "#/components/schemas/Subscription"
        default:
          $ref: "#/components/responses/ErrorResponse"
  /subscriptions/{id}:
    get:
      operationId: get_subscription
      description: Get a single subscription.
      tags:
      - subscriptions
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: The subscription.
          content:
            application/json:
              schema:
                required:
                - data
                properties:
                  data:
                    $ref: "#/components/schemas/Subscription"
        default:
          $ref: "#/components/responses/ErrorResponse"
    put:
      operationId: update_subscription
      description: Update a subscription.
      tags:
      - subscriptions
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      requestBody:
        $ref: "#/components/requestBodies/UpdateSubscription"
      responses:
        "200":
          description: The updated subscription.
          content:
            application/json:
              schema:
                required:
                - data
                properties:
                  data:
                    $ref: "#/components/schemas/Subscription"
        default:
          $ref: "#/components/responses/ErrorResponse"
    delete:
      operationId: delete_subscription
      description: |
        Deletes a subscription.

        This action can not be undone.
      tags:
      - subscriptions
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        "204":
          description: Subscription was deleted successfully
        default:
          $ref: "#/components/responses/ErrorResponse"

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer

  callbacks: {}

  parameters: {}

  requestBodies:
    CreatePurchaseOrder:
      description: Create a purchase order.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/CreatePurchaseOrder"
    CreateSubscription:
      description: Create a subscription.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/CreateSubscription"
    UpdateSubscription:
      description: Update a subscription.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/UpdateSubscription"

  responses:
    ErrorResponse:
      description: Error response
      content:
        application/json:
          schema:
            required:
            - errors
            properties:
              errors:
                type: array
                items:
                  $ref: "#/components/schemas/Error"

  schemas:
    ExternalId:
      description: |
        The external id set by the ERP system. It does not have to be a UUID and
        can be any non empty string desired.
      type: string
      example: 21b31bc7-1267-4335-893c-d7fe4706a238
      maxLength: 255
    InternalId:
      description: |
        The internal id set by the Vic API. The ids provided may be integers, UUIDs,
        or a different non numerical value.
      type: string
      example: 123245, 21b31bc7-1267-4335-893c-d7fe4706a238
      maxLength: 255
    SystemType:
      enum:
        - internal
        - external
    Monetary:
      type: string
      format: decimal
    Currency:
      description: The ISO-4217 currency code.
      type: string
      format: ISO-4217
      maxLength: 3
    CallbackUrl:
      description: |
        The url to receive the callback requests.

        It *must* be an `https` url.
      type: string
      default: "https://example.com/events"
    Error:
      type: object
      description: |
        Represents an error within the system. Note that `field` may not always
        be present, but `message` will always be present.

        For nested fields, the format will be as follows:

        - `purchase_order.line_items`
        - `purchase_order.line_items.0.product_number`
      required:
      - message
      properties:
        field:
          type: string
          nullable: true
        message:
          type: string
    CreateSubscription:
      type: object
      required:
      - access_token
      - callback_url
      - expires_at
      - version
      properties:
        access_token:
          type: string
        callback_url:
          $ref: "#/components/schemas/CallbackUrl"
        expires_at:
          description: |
            The time that the subscription expires at. It *must* be in the
            future.
          type: string
          format: date-time
        version:
          $ref: "#/components/schemas/SubscriptionVersion"
    UpdateSubscription:
      type: object
      properties:
        access_token:
          type: string
        callback_url:
          $ref: "#/components/schemas/CallbackUrl"
        expires_at:
          description: |
            The time that the subscription expires at. It *must* be in the
            future.
          type: string
          format: date-time
        version:
          $ref: "#/components/schemas/SubscriptionVersion"
    SubscriptionVersion:
      description: The webhook subscription version.
      enum:
        - v0
        - v1
    Subscription:
      type: object
      required:
      - internal_id
      - callback_url
      - access_token
      - expires_at
      - version
      properties:
        internal_id:
          $ref: "#/components/schemas/InternalId"
        access_token:
          type: string
        callback_url:
          $ref: "#/components/schemas/CallbackUrl"
        expires_at:
          type: string
          format: date-time
        version:
          $ref: "#/components/schemas/SubscriptionVersion"
    DimensionRef:
      type: object
      description: A reference object to a dimension object.
      properties:
        internal_id:
          type: string
          maxLength: 255
        external_id:
          type: string
          maxLength: 255
        name:
          type: string
          maxLength: 255
          nullable: true
    PurchaseOrderStatus:
      enum:
      - open
      - closed
    PurchaseOrderItem:
      type: object
      required:
      - internal_id
      properties:
        internal_id:
          type: string
          maxLength: 255
        product_number:
          type: string
          maxLength: 255
        product_description:
          type: string
          maxLength: 255
        unit_of_measure:
          type: string
          maxLength: 255
        unit_amount:
          oneOf:
          - $ref: "#/components/schemas/Monetary"
          nullable: true
        line_item_total:
          oneOf:
          - $ref: "#/components/schemas/Monetary"
          nullable: true
        dimensions:
          type: array
          items:
            $ref: "#/components/schemas/DimensionRef"
    PurchaseOrder:
      type: object
      required:
      - internal_id
      - internal_updated_at
      - status
      - items
      properties:
        internal_id:
          type: string
          maxLength: 255
        external_id:
          type: string
          maxLength: 255
        vendor_id:
          type: string
          maxLength: 255
        internal_updated_at:
          type: string
          format: date-time
        issued_on:
          type: string
          format: date
        po_number:
          type: string
          maxLength: 255
        deliver_on:
          type: string
          format: date
        amount:
          oneOf:
          - $ref: "#/components/schemas/Monetary"
          nullable: true
        currency_id:
          oneOf:
          - $ref: "#/components/schemas/Currency"
          nullable: true
        status:
          $ref: "#/components/schemas/PurchaseOrderStatus"
        description:
          type: string
          maxLength: 255
        items:
          type: array
          items:
            $ref: "#/components/schemas/PurchaseOrderItem"
    CreatePurchaseOrderItemEmbedded:
      properties:
        product_number:
          type: string
          nullable: true
          maxLength: 255
        product_description:
          type: string
          nullable: true
          maxLength: 255
        unit_of_measure:
          type: string
          nullable: true
          maxLength: 255
        quantity:
          type: string
          format: decimal
          nullable: true
        unit_amount:
          oneOf:
          - $ref: "#/components/schemas/Monetary"
          nullable: true
        line_item_total:
          oneOf:
          - $ref: "#/components/schemas/Monetary"
          nullable: true
        dimensions:
          type: array
          items:
            $ref: "#/components/schemas/DimensionRef"
    CreatePurchaseOrder:
      required:
      - status
      properties:
        external_id:
          type: string
          nullable: true
          maxLength: 255
        issued_on:
          type: string
          format: date
          nullable: true
        po_number:
          type: string
          nullable: true
          maxLength: 255
        deliver_on:
          type: string
          format: date
          nullable: true
        amount:
          oneOf:
          - $ref: "#/components/schemas/Monetary"
          nullable: true
        currency_id:
          oneOf:
          - $ref: "#/components/schemas/Currency"
          nullable: true
        description:
          type: string
          nullable: true
          maxLength: 255
        requestor:
          type: string
          nullable: true
          maxLength: 255
        quantity_received:
          type: string
          format: decimal
          nullable: true
        created_on:
          type: string
          format: date
          nullable: true
        status:
          $ref: "#/components/schemas/PurchaseOrderStatus"
        items:
          type: array
          items:
            $ref: "#/components/schemas/CreatePurchaseOrderItemEmbedded"
