openapi: 3.0.3
info:
  version: 0.3.16
  contact: {}
  title: Vic.Api
  description: |
    Vic.Api allows you to connect an *ERP* to the Vic.ai product suite.

servers:
- url: 'https://api.us.dev.vic.ai/v1'
  description: 'development server, US'
- url: 'https://api.no.dev.vic.ai/v1'
  description: 'development server, NO'
- url: 'https://api.us.stage.vic.ai/v1'
  description: 'staging server, US'
- url: 'https://api.no.stage.vic.ai/v1'
  description: 'staging server, NO'
- url: 'https://api.us.vic.ai/v1'
  description: 'production server, US'
- url: 'https://api.no.vic.ai/v1'
  description: 'production server, NO'

tags:
- name: purchase orders
- name: subscriptions

paths:
  "/purchase_orders":
    post:
      description: Use this request to create a purchase order
      summary: Create a purchase order
      operationId: createPurchaseOrder
      tags:
        - purchase orders
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreatePurchaseOrder"
      responses:
        '200':
          description: Purchase order created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PurchaseOrder'
          default:
            description: unexpected error
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Error'
  "/purchase_orders/{id}":
    get:
      description: Use this request to get data for a single purchase order
      summary: Get a purchase order
      operationId: getPurchaseOrder
      tags:
        - purchase orders
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
        - name: use_system
          in: query
          schema:
            $ref: "#/components/schemas/SystemType"
      responses:
        '200':
          description: Purchase order retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PurchaseOrder'
          default:
            description: unexpected error
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Error'
  "/subscriptions":
    get:
      operationId: list_subscriptions
      description: List all subscriptions.
      tags:
      - subscriptions
      responses:
        "200":
          description: List all of the subscriptions
          content:
            application/json:
              schema:
                required:
                - data
                properties:
                  data:
                    type: array
                    items:
                      $ref: "#/components/schemas/Subscription"
        default:
          $ref: "#/components/responses/ErrorResponse"
    post:
      operationId: create_subscription
      description: Create a subscription.
      tags:
      - subscriptions
      requestBody:
        $ref: "#/components/requestBodies/CreateSubscription"
      responses:
        "201":
          description: Subscription was created successfully.
          content:
            application/json:
              schema:
                required:
                - data
                properties:
                  data:
                    $ref: "#/components/schemas/Subscription"
        default:
          $ref: "#/components/responses/ErrorResponse"
  "/subscriptions/{id}":
    get:
      operationId: get_subscription
      description: Get a single subscription.
      tags:
      - subscriptions
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: The subscription.
          content:
            application/json:
              schema:
                required:
                - data
                properties:
                  data:
                    $ref: "#/components/schemas/Subscription"
        default:
          $ref: "#/components/responses/ErrorResponse"
    put:
      operationId: update_subscription
      description: Update a subscription.
      tags:
      - subscriptions
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      requestBody:
        $ref: "#/components/requestBodies/UpdateSubscription"
      responses:
        "200":
          description: The updated subscription.
          content:
            application/json:
              schema:
                required:
                - data
                properties:
                  data:
                    $ref: "#/components/schemas/Subscription"
        default:
          $ref: "#/components/responses/ErrorResponse"
    delete:
      operationId: delete_subscription
      description: |
        Deletes a subscription.

        This action can not be undone.
      tags:
      - subscriptions
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        "204":
          description: Subscription was deleted successfully
        default:
          $ref: "#/components/responses/ErrorResponse"

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer

  callbacks: {}

  parameters: {}

  requestBodies:
    CreateSubscription:
      description: Create a subscription.
      content:
        application/json:
          schema:
            required:
            - access_token
            - callback_url
            - expires_at
            - version
            properties:
              access_token:
                type: string
              callback_url:
                $ref: "#/components/schemas/CallbackUrl"
              expires_at:
                description: |
                  The time that the subscription expires at. It *must* be in the
                  future.
                type: string
                format: date-time
              version:
                $ref: "#/components/schemas/SubscriptionVersion"
    UpdateSubscription:
      description: Update a subscription.
      content:
        application/json:
          schema:
            properties:
              access_token:
                type: string
              callback_url:
                $ref: "#/components/schemas/CallbackUrl"
              expires_at:
                description: |
                  The time that the subscription expires at. It *must* be in the
                  future.
                type: string
                format: date-time
              version:
                $ref: "#/components/schemas/SubscriptionVersion"

  responses:
    ErrorResponse:
      description: Error response
      content:
        application/json:
          schema:
            required:
            - errors
            properties:
              errors:
                type: array
                items:
                  $ref: "#/components/schemas/Error"

  schemas:
    ExternalId:
      description: |
        The external id set by the ERP system. It does not have to be a UUID and
        can be any string desired.
      type: string
      example: 21b31bc7-1267-4335-893c-d7fe4706a238
      maxLength: 255
    SystemType:
      enum:
        - internal
        - external
    CallbackUrl:
      description: |
        The url to receive the callback requests.

        It *must* be an `https` url.
      type: string
      default: "https://example.com/events"
    Error:
      type: object
      description: |
        Represents an error within the system. Note that `field` may not always
        be present, but `message` will always be present.

        For nested fields, the format will be as follows:

        - `purchase_order.line_items`
        - `purchase_order.line_items.0.product_number`
      required:
      - message
      properties:
        field:
          type: string
          nullable: true
        message:
          type: string
    CreateSubscription:
      type: object
      required:
      - access_token
      - expires_at
      - version
      properties:
        access_token:
          type: string
        expires_at:
          type: string
          format: date-time
        version:
          $ref: "#/components/schemas/SubscriptionVersion"
    UpdateSubscription:
      type: object
      required:
      - access_token
      - expires_at
      - version
      properties:
        access_token:
          type: string
        expires_at:
          type: string
          format: date-time
        version:
          $ref: "#/components/schemas/SubscriptionVersion"
    SubscriptionVersion:
      description: The webhook subscription version.
      enum:
        - v0
        - v1
    Subscription:
      type: object
      required:
      - internal_id
      - callback_url
      - access_token
      - expires_at
      - version
      properties:
        internal_id:
          type: string
        access_token:
          type: string
        callback_url:
          $ref: "#/components/schemas/CallbackUrl"
        expires_at:
          type: string
          format: date-time
        version:
          $ref: "#/components/schemas/SubscriptionVersion"
    CreatePurchaseOrder:
      type: object
      required:
      - status
      properties:
        external_id:
          $ref: "#/components/schemas/ExternalId"
        issued_on:
          type: string
          format: date-time
          description: The date the purchase order was issued.
        po_number:
          type: string
          description: The purchase order number.
        deliver_on:
          type: string
          format: date-time
          description: The date the purchase order should be delivered.
        amount:
          type: decimal
          description: The total amount of the purchase order.
        currency_id:
          type: string
          description: The currency id of the purchase order. 
        description:
          type: string
          description: The description of the purchase order.
        requestor:
          type: string
          description: The requestor of the purchase order.
        quantity_received:
          type: decimal
          description: The quantity received of the purchase order.
        created_on:
          type: string
          format: date-time
          description: The date the purchase order was created.
        status:
          $ref: "#/components/schemas/Status"
        items:
          type: array
          items:
            $ref: "#/components/schemas/PurchaseOrderLineItem"
            description: |
              The line items of the purchase order.
    Status:
      enum:
        - open
        - closed
    PurchaseOrderLineItem:
      type: object
      properties:
        product_number:
          type: string
          description: The product number of the line item.
        product_description:
          type: string
          description: The product description of the line item.
        unit_of_measure:
          type: string
          description: The unit of measure of the line item.
        quantity:
          type: decimal
          description: The quantity of the line item.
        unit_amount:
          type: decimal
          description: The unit amount of the line item.
        line_item_total:
          type: decimal
          description: The line item total of the line item.
        dimensions:
          type: array
          nullable: true
          items: "#/components/schemas/ReferenceInput"
    ReferenceInput:
      type: object
      description: |
          A simple input object that just has an `internal_id` and 
          `external_id`. At least one must be present. If both are provided, 
          `internal_id` takes priority.
      properties:
        internal_id:
          type: string
          description: The internal id of the object.
        external_id:
          $ref: "#/components/schemas/ExternalId"

